### PR TITLE
feat: demo event usage

### PR DESCRIPTION
**Pull request by asinbow**
This is not final version, but a demo to make event work.
@durs Your suggestion is welcome.

### CODE REVIEW

**Comment by durs** [comment]
Hi, what are the differences
    // TODO START @asinbow Write proper code
    // 1. get event name from dispIdMember and IDispatch->IConnectionPoints->...
	// 2. invoke callback by event name
	if ((wFlags & DISPATCH_METHOD) != 0) {
             ..........
	}
	// TODO END @asinbow Write proper code

and below

	// Call property as method
	if ((wFlags & DISPATCH_METHOD) != 0) {
             .................
	}

**Comment by durs** [comment]
Conflict with other features (mocha test)
I`m corrected your "TODO START @asinbow Write proper code"

>mocha test
  COM from JS object
    1) call method
    2) call method with object argument
  Excel with JS object
    3) invoke test simple property
    4) invoke test object property
    5) invoke test array property
    6) invoke test method

**Comment by asinbow** [comment]
Thanks for merge, although I did mean it. Because it's now just a concept verfication.
I will finish rest works in 1 week.

**Comment by asinbow** [comment]
Actually no difference. I did that just because `index` is empty.
Now if you can find a way to parse event `name` from `dispIdMember` and `IConnectionPoint`, all previous work can be reused.

https://github.com/asinbow/CppActiveXEventDemo/blob/master/CppActiveXEventDemo/CppActiveXEventDemo.cpp

**Pull request merged**
